[tasks.check]
command = "cargo"
args = ["check"]

[tasks.test]
command = "cargo"
args = ["test", "--quiet"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--all", "--", "--W", "clippy::pedantic"]

[tasks.dev]
command = "cargo"
args = [
  "watch",
  "-x",
  "check",
  "-x",
  "clippy --all -- --W clippy::pedantic",
  "-x",
  "test",
  "--quiet",
]
